version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - mysql
      - php
      - npm

  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    restart: always

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["/bin/sh", "-c", "npm install && npm run build"]
    working_dir: /var/www/html

  php-commands:
    build:
      context: .
      dockerfile: php.prod.dockerfile
    entrypoint: ["/bin/sh", "-c", "composer install --optimize-autoloader --no-dev && php artisan optimize && php artisan view:cache && php artisan event:cache"]
    depends_on:
      - mysql
      - php
